import type { Node, Edge } from '@xyflow/react'
import type { GateType } from '../engine/gateLogic'
import type { ComboType } from '../engine/combinationalLogic'

// ─── Helpers ──────────────────────────────────────────────────────────────────
function sanitizeId(id: string): string {
    return id.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^[0-9]/, 'n$&')
}

function edgeWireName(e: Edge): string {
    return `w_${sanitizeId(e.source)}_to_${sanitizeId(e.target)}_${sanitizeId(e.id.slice(-6))}`
}

// ─── Gate → Verilog primitive ─────────────────────────────────────────────────
const GATE_PRIM: Partial<Record<GateType, string>> = {
    AND: 'and', OR: 'or', NOT: 'not',
    NAND: 'nand', NOR: 'nor', XOR: 'xor', XNOR: 'xnor',
}

const COMBO_COMMENTS: Partial<Record<ComboType, string>> = {
    HALF_ADDER: '// Half Adder: Sum=A^B  Carry=A&B',
    FULL_ADDER: '// Full Adder: Sum=A^B^Cin  Cout=majority(A,B,Cin)',
    MUX_2_1: '// 2:1 MUX: Y = S?B:A',
    MUX_4_1: '// 4:1 MUX',
}

// ─── Main export ──────────────────────────────────────────────────────────────
export function exportToVerilog(nodes: Node[], edges: Edge[], moduleName = 'circuit_top'): string {
    const safeModule = moduleName.replace(/[^\w]/g, '_') || 'circuit_top'
    const lines: string[] = []
    const now = new Date().toISOString()

    // Classify nodes
    const inputs = nodes.filter((n) => n.type === 'inputNode' || (n.data as Record<string, unknown>)?.gateType === 'INPUT')
    const outputs = nodes.filter((n) => n.type === 'outputNode' || (n.data as Record<string, unknown>)?.gateType === 'OUTPUT')
    const clocks = nodes.filter((n) => (n.data as Record<string, unknown>)?.gateType === 'CLOCK')
    const gates = nodes.filter((n) => n.type === 'gateNode' && !['INPUT', 'OUTPUT', 'CLOCK'].includes(String((n.data as Record<string, unknown>)?.gateType)))
    const combos = nodes.filter((n) => n.type === 'comboNode')

    // Build wire map: edgeId → wireName
    const wireMap = new Map<string, string>()
    edges.forEach((e) => wireMap.set(e.id, edgeWireName(e)))

    // Build output-wire map: "nodeId:handleIndex" → wireName
    // For a node that outputs to multiple targets, each edge has a distinct wire
    const nodeOutputWires = new Map<string, string>() // key = "nodeId:handleIdx"
    edges.forEach((e) => {
        const handleIdx = parseInt((e.sourceHandle ?? '0').replace('output-', ''), 10) || 0
        const key = `${e.source}:${handleIdx}`
        if (!nodeOutputWires.has(key)) nodeOutputWires.set(key, wireMap.get(e.id)!)
    })

    // Helper: get the wire name driving a node's input pin
    function inputWire(nodeId: string, inputIdx: number): string {
        const e = edges.find((ed) => ed.target === nodeId && ed.targetHandle === `input-${inputIdx}`)
        return e ? (wireMap.get(e.id) ?? `1'b0`) : `1'b0`
    }

    // Header
    lines.push(`// =======================================================`)
    lines.push(`// Generated by CircuitForge — ${now}`)
    lines.push(`// Module: ${safeModule}`)
    lines.push(`// Nodes: ${nodes.length}  Edges: ${edges.length}`)
    lines.push(`// =======================================================`)
    lines.push('')

    // Module declaration
    const portList: string[] = []
    inputs.forEach((n, i) => portList.push(`in_${i}`))
    clocks.forEach((n, i) => portList.push(`clk_${i}`))
    outputs.forEach((n, i) => portList.push(`out_${i}`))
    lines.push(`module ${safeModule} (`)
    portList.forEach((p, i) => lines.push(`    ${i < portList.length - 1 ? p + ',' : p}`))
    lines.push(`);`)
    lines.push('')

    // Port declarations
    inputs.forEach((_, i) => lines.push(`    input  wire in_${i};`))
    clocks.forEach((_, i) => lines.push(`    input  wire clk_${i};`))
    outputs.forEach((_, i) => lines.push(`    output wire out_${i};`))
    lines.push('')

    // Internal wires
    if (edges.length > 0) {
        lines.push(`    // Internal wires`)
        const internalWires = new Set<string>()
        edges.forEach((e) => {
            const w = wireMap.get(e.id)
            if (w) internalWires.add(w)
        })
        internalWires.forEach((w) => lines.push(`    wire ${w};`))
        lines.push('')
    }

    // Input assignments
    lines.push(`    // ── Input assignments ──────────────────────────────`)
    inputs.forEach((n, i) => {
        const e = edges.find((ed) => ed.source === n.id)
        if (e) lines.push(`    assign ${wireMap.get(e.id)} = in_${i};`)
    })
    clocks.forEach((n, i) => {
        const e = edges.find((ed) => ed.source === n.id)
        if (e) lines.push(`    assign ${wireMap.get(e.id)} = clk_${i};`)
    })
    lines.push('')

    // Gate instantiations
    if (gates.length > 0) {
        lines.push(`    // ── Gate primitives ────────────────────────────────`)
        gates.forEach((n) => {
            const data = n.data as Record<string, unknown>
            const gateType = data.gateType as GateType
            const prim = GATE_PRIM[gateType] ?? gateType.toLowerCase()
            const numIn = (data.numInputs as number) ?? 2
            const safeName = sanitizeId(n.id)
            const outputEdge = edges.find((e) => e.source === n.id)
            const outWire = outputEdge ? (wireMap.get(outputEdge.id) ?? `w_${safeName}_out`) : `w_${safeName}_out`
            const inputWires = Array.from({ length: numIn }, (_, idx) => inputWire(n.id, idx))
            if (gateType === 'NOT') {
                lines.push(`    not ${safeName} (${outWire}, ${inputWires[0]});`)
            } else {
                lines.push(`    ${prim} ${safeName} (${outWire}, ${inputWires.join(', ')});`)
            }
        })
        lines.push('')
    }

    // Combo modules — instantiated as sub-modules
    if (combos.length > 0) {
        lines.push(`    // ── Combinational components ───────────────────────`)
        combos.forEach((n) => {
            const data = n.data as Record<string, unknown>
            const cType = data.componentType as ComboType
            const comment = COMBO_COMMENTS[cType]
            if (comment) lines.push(`    ${comment}`)
            const safeName = sanitizeId(n.id)
            const outputEdges = edges.filter((e) => e.source === n.id)
            const numIn = (data.inputValues as unknown[])?.length ?? 2
            const inputWires = Array.from({ length: numIn }, (_, idx) => inputWire(n.id, idx))
            const outputWires = outputEdges.map((e) => wireMap.get(e.id) ?? `1'bz`)
            lines.push(`    // ${cType}: inputs=[${inputWires.join(', ')}]`)
            lines.push(`    //           outputs=[${outputWires.join(', ')}]`)
            lines.push(`    // (Instantiate a ${cType.toLowerCase()} module here)`)
            lines.push(`    // ${cType}_module ${safeName} (${[...outputWires, ...inputWires].join(', ')});`)
            lines.push('')
        })
    }

    // Output assignments
    lines.push(`    // ── Output assignments ─────────────────────────────`)
    outputs.forEach((n, i) => {
        const e = edges.find((ed) => ed.target === n.id)
        if (e) lines.push(`    assign out_${i} = ${wireMap.get(e.id) ?? `1'b0`};`)
        else lines.push(`    assign out_${i} = 1'b0;  // unconnected`)
    })
    lines.push('')

    lines.push(`endmodule`)
    lines.push('')

    return lines.join('\n')
}

// ─── Download .v file ─────────────────────────────────────────────────────────
export function downloadVerilog(nodes: Node[], edges: Edge[], name: string): void {
    try {
        const verilog = exportToVerilog(nodes, edges, name.replace(/\s+/g, '_').toLowerCase())
        const blob = new Blob([verilog], { type: 'text/plain;charset=utf-8' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `${name.replace(/[^\w\s-]/g, '').replace(/\s+/g, '-').toLowerCase() || 'circuit'}.v`
        document.body.appendChild(a)
        a.click()
        setTimeout(() => { document.body.removeChild(a); URL.revokeObjectURL(url) }, 100)
    } catch (err) {
        console.error('[verilogExport]', err)
        throw new Error('Verilog export failed')
    }
}
